### ISSUE TITLE
Is there any implementation of tensorflow 1.x version?

### ISSUE THREAD

**Issue by davsolai** [Leonardo-Blanger/RefineDet_TensorFlow#3]
Thank you for your share!

Is there any implementation of tensorflow 1.x version?

**Comment by Leonardo-Blanger** [comment]
Actually, there are.
I only recently moved everything to TF 2.0.
If you revert back to the last commit before this year, you should get the previous version.
But be careful, because the code was still very raw and baddly structured. Also, I never properly finished it to the point of running the full training and evaluation as was in the paper.

I started it last year and never had time to finish. Then TF 2.0 came up and I abandoned it, until now.

**Comment by davsolai** [comment]
Okay. Thanks for the answer!
